### PR TITLE
Report builder - FR.OS version

### PR DESCRIPTION
**Pull request by KirillKornienko**
Now ReportBuilder using latest version FR.OS

### CODE REVIEW

**Comment by KirillKornienko** [comment]
@ekondur

**Comment by ekondur** [comment]
Hi, @KirillKornienko ,
When do you plan it publish to nuget?

**Comment by KirillKornienko** [comment]
Hi, @ekondur . Yes, I'm doing it right now

**Comment by KirillKornienko** [comment]
> Hi, @KirillKornienko ,
> When do you plan it publish to nuget?

nuget.org requires a license information
image

**Comment by ekondur** [comment]
Yes, we talked it before with Aleksandr, but i dont't now how can I link licence between project,

https://github.com/FastReports/FastReport/issues/241

**Comment by KirillKornienko** [comment]
@ekondur , done. https://www.nuget.org/packages/FastReport.ReportBuilder/2021.1.0

**Comment by ekondur** [comment]
Thank you @KirillKornienko

**Comment by ekondur** [comment]
I can see on nuget now but without icon, thaks again @KirillKornienko

**Pull request merged**
